services:
  web:
    build: .
    pull_policy: build
    container_name: cmdb_web
    environment:
      MYSQL_DATABASE: cmdb
      MYSQL_USER: cmdb_user
      MYSQL_PASSWORD: dbpassone
      MYSQL_HOST: db

      # Active Directory (AD) Environment Variables
      AD_SERVER: "ldap://homehardware.ca"
      AD_PORT: 389  # Use 636 for LDAPS
      AD_BASE_DN: "DC=homehardware,DC=ca"
      AD_USER_DN: "CN=Mackay, Colin,OU=IT,OU=Stj,OU=Home,DC=homehardware,DC=ca"
      AD_PASSWORD: "RoadRoversonEarth!"
      AD_GROUP_FILTER: "(objectClass=group)"
      AD_USER_FILTER: "(objectClass=user)"
      
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: cmdb_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hardware123
      MYSQL_DATABASE: cmdb
      MYSQL_USER: cmdb_user
      MYSQL_PASSWORD: dbpassone
      MYSQL_HOST: db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cmdb_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: hardware123

volumes:
  db_data:

x-deploy:
  git:
    repository: https://github.com/zxarr/cmdb-project
    branch: main
