version: '3.8'

services:
  web:
    build: .
    container_name: cmdb_web
    ports:
      - "8084:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: cmdb_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hardware123
      MYSQL_DATABASE: cmdb
      MYSQL_USER: cmdb_user
      MYSQL_PASSWORD: dbpassone
    ports:
      - "3316:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cmdb_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: hardware123

volumes:
  db_data:

x-deploy:
  git:
    repository: https://github.com/zxarr/cmdb-project
    branch: main