
services:
  web:
    build: .
    pull_policy: build
    container_name: cmdb_web
    environment:
      MYSQL_DATABASE: cmdb
      MYSQL_USER: cmdb_user
      MYSQL_PASSWORD: dbpassone
      MYSQL_HOST: db
    ports:
      - "8084:80"
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: cmdb_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hardware123
      MYSQL_DATABASE: cmdb
      MYSQL_USER: cmdb_user
      MYSQL_PASSWORD: dbpassone
      MYSQL_HOST: db
    ports:
      - "3316:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cmdb_phpmyadmin
    restart: always
    ports:
      - "8085:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: hardware123

volumes:
  db_data:

x-deploy:
  git:
    repository: https://github.com/zxarr/cmdb-project
    branch: main